apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-monitor
  # ВАЖНО: Лейбл ниже должен совпадать с тем, что ищет ваш Helm-Prometheus.
  # Обычно это 'release: kube-stack' (имя вашего helm release)
  labels:
    release: kube-stack
spec:
  selector:
    matchLabels:
      app: node-app
  endpoints:
  - port: web
    interval: 15s
    path: /metrics
