name: Local Docker CD

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop old container
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        docker stop node-demo-app
        docker rm node-demo-app
        $ErrorActionPreference = 'Continue'
      shell: powershell

    - name: Build Docker image
      run: docker build -t nodejs-demo-app:local .

    - name: Run new container
      run: docker run -d --name node-demo-app -p 3000:3000 nodejs-demo-app:local
