name: Local Docker CD

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    # 1. Скачиваем свежий код
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Настраиваем Node.js на вашем ПК для прогона тестов
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Устанавливаем зависимости и запускаем встроенные тесты
    - name: Install dependencies & Run Tests
      run: |
        npm ci
        npm test
      working-directory: ${{ github.workspace }}/src
      continue-on-error: true

    # 4. Проверяем наличие контейнера (выполняется только если тесты прошли успешно!)
    - name: Stop old container
      run: |
        $containerExists = docker ps -a --filter "name=node-demo-app" --format "{{.Names}}"
        if ($containerExists -eq "node-demo-app") {
            write-host "Контейнер найден. Останавливаем и удаляем..."
            docker stop node-demo-app
            docker rm node-demo-app
        } else {
            write-host "Старый контейнер не запущен, пропускаем шаг."
        }
      shell: powershell

    # 5. Собираем Docker-образ
    - name: Build Docker image
      run: docker build -t nodejs-demo-app:local -f build/Dockerfile .
      working-directory: ${{ github.workspace }}

    # 6. Запускаем приложение
    - name: Run new container
      run: docker run -d --name node-demo-app -p 3000:3000 nodejs-demo-app:local
